Transform: AWS::Serverless-2016-10-31
Resources:
  Index:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Cors: '*'
            Path: /
            Method: POST